# Generated by Django 4.1.2 on 2022-10-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(default='2001-01-01', verbose_name='Дата рождения'),
        ),
    ]
