# Generated by Django 4.1.2 on 2022-10-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_firstname_userprofile_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
    ]
