# Generated by Django 4.1.2 on 2022-10-11 14:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_alter_user_creation_datetime_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lastname',
        ),
    ]
