# Generated by Django 4.1.2 on 2022-11-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_remove_userprofile_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Номер телефона'),
        ),
    ]
