# Generated by Django 4.1.2 on 2022-11-02 08:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0006_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
