# Generated by Django 4.1.2 on 2022-11-02 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_userprofile_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked_until',
            field=models.DateField(default=datetime.date(2000, 1, 1), verbose_name='Заблокирован до'),
        ),
    ]
