# Generated by Django 4.1.2 on 2022-11-03 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_blocked_until'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='profiles',
        ),
    ]
