# Generated by Django 4.1.2 on 2022-10-07 12:47

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('guid',
                 models.CharField(db_column='guid', default=uuid.uuid4, editable=False, max_length=64, primary_key=True,
                                  serialize=False)),
                ('creation_date', models.DateField(auto_now_add=True, db_column='creation_date')),
                ('topic', models.CharField(max_length=1024)),
                ('article_body', models.TextField()),
                ('author_id', models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE,
                                                to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleHistory',
            fields=[
                ('guid',
                 models.CharField(db_column='guid', default=uuid.uuid4, editable=False, max_length=64, primary_key=True,
                                  serialize=False)),
                ('record_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('change_type', models.CharField(
                    choices=[('Создание', 'Создание'), ('Изменение', 'Редактирование'), ('Блокировка', 'Блокировка')],
                    max_length=1024, verbose_name='Вид изменения')),
                ('article_uid', models.ForeignKey(db_column='article_uid', on_delete=django.db.models.deletion.CASCADE,
                                                  to='articles.article')),
                ('changer_id', models.ForeignKey(db_column='editor_id', on_delete=django.db.models.deletion.DO_NOTHING,
                                                 to=settings.AUTH_USER_MODEL, verbose_name='Автор изменения')),
            ],
        ),
    ]
