# Generated by Django 4.1.2 on 2022-10-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('articles', '0002_articlehistory_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlehistory',
            name='blocked',
        ),
        migrations.AddField(
            model_name='article',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
