# Generated by Django 4.1.2 on 2022-10-19 14:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_articlecategory_articles_articlecategory_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='guid',
            field=models.CharField(db_column='guid', default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False),
        ),
    ]
