# Generated by Django 4.1.2 on 2022-10-20 09:49

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('articles', '0008_alter_comment_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date_added',
            field=models.DateField(db_column='dts', default=datetime.date(2022, 10, 20), verbose_name='Дата создания'),
        ),
    ]
