# Generated by Django 4.1.2 on 2022-10-20 09:51

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0009_notification_date_added'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='ArticleLike',
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('guid',
                 models.CharField(db_column='guid', default=uuid.uuid4, editable=False, max_length=64, primary_key=True,
                                  serialize=False)),
                ('event_type', models.CharField(choices=[('Нравится', 'Нравится'), ('Не нравится', 'Не нравится')],
                                                default='Нравится', max_length=32)),
                ('comment_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.comment',
                                                  verbose_name='Статья')),
                ('user_id',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL,
                                   verbose_name='Автор')),
            ],
        ),
    ]
