# Generated by Django 4.1.2 on 2022-10-20 09:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('articles', '0011_alter_notification_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlelike',
            name='date_added',
            field=models.DateField(db_column='dts', default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='date_added',
            field=models.DateField(db_column='dts', default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
