# Generated by Django 4.1.2 on 2022-10-20 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_alter_comment_time_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='article_uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.article', verbose_name='Статья'),
        ),
    ]
