# Generated by Django 4.1.2 on 2022-10-20 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('articles', '0015_alter_comment_time_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['message_readed', '-date_added']},
        ),
        migrations.AddField(
            model_name='notification',
            name='article_uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.article',
                                    verbose_name='Статья'),
        ),
    ]
