# Generated by Django 4.1.2 on 2022-10-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('articles', '0017_alter_article_options_alter_article_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlelike',
            name='event_type',
        ),
        migrations.AddField(
            model_name='articlelike',
            name='event_counter',
            field=models.IntegerField(default=1, verbose_name='Счетчик'),
        ),
    ]
