# Generated by Django 4.1.2 on 2022-10-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_remove_commentlike_event_type_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='articlelike',
            constraint=models.UniqueConstraint(fields=('user_id', 'article_uid'), name='articles_articlelike_unique'),
        ),
        migrations.AddConstraint(
            model_name='commentlike',
            constraint=models.UniqueConstraint(fields=('user_id', 'comment_uid'), name='articles_commentlike_unique'),
        ),
    ]
