# Generated by Django 4.1.2 on 2022-11-02 08:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('articles', '0021_alter_articlecategory_article_guid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-creation_date'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'verbose_name': 'Категория статьи', 'verbose_name_plural': 'Категории статей'},
        ),
        migrations.AlterModelOptions(
            name='articlehistory',
            options={'verbose_name': 'История статьи', 'verbose_name_plural': 'История статей'},
        ),
        migrations.AlterModelOptions(
            name='articlelike',
            options={'verbose_name': 'Лайк (статьи)', 'verbose_name_plural': 'Лайки (статей)'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_added', 'time_added'], 'verbose_name': 'Комментарий',
                     'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='commentlike',
            options={'verbose_name': 'Лайк (комментария)', 'verbose_name_plural': 'Лайки (комментариев)'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['message_readed', '-date_added'], 'verbose_name': 'Уведомление',
                     'verbose_name_plural': 'Уведомления'},
        ),
    ]
