# Generated by Django 4.1.2 on 2022-11-02 09:08

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0023_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_body',
            field=models.TextField(default='ici', verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author_id',
            field=models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='article',
            name='blocked',
            field=models.BooleanField(default=False, verbose_name='Заблокирована'),
        ),
        migrations.AlterField(
            model_name='article',
            name='creation_date',
            field=models.DateField(auto_now_add=True, db_column='creation_date', db_index=True,
                                   verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='article',
            name='guid',
            field=models.CharField(db_column='guid', default=uuid.uuid4, editable=False, max_length=64,
                                   primary_key=True, serialize=False, verbose_name='Ключ'),
        ),
        migrations.AlterField(
            model_name='article',
            name='moderation',
            field=models.BooleanField(default=True, verbose_name='На модерации'),
        ),
        migrations.AlterField(
            model_name='article',
            name='topic',
            field=models.CharField(max_length=1024, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='article_guid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article',
                                    verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='category_guid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.category',
                                    verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='guid',
            field=models.CharField(db_column='guid', default=uuid.uuid4, editable=False, max_length=64,
                                   primary_key=True, serialize=False, verbose_name='Ключ'),
        ),
        migrations.AlterField(
            model_name='articlehistory',
            name='article_uid',
            field=models.ForeignKey(db_column='article_uid', on_delete=django.db.models.deletion.CASCADE,
                                    to='articles.article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='articlehistory',
            name='guid',
            field=models.CharField(db_column='guid', default=uuid.uuid4, editable=False, max_length=64,
                                   primary_key=True, serialize=False, verbose_name='Ключ'),
        ),
        migrations.AlterField(
            model_name='articlelike',
            name='guid',
            field=models.CharField(db_column='guid', default=uuid.uuid4, editable=False, max_length=64,
                                   primary_key=True, serialize=False, verbose_name='Ключ'),
        ),
        migrations.AlterField(
            model_name='category',
            name='guid',
            field=models.CharField(db_column='guid', default=uuid.uuid4, editable=False, max_length=64,
                                   primary_key=True, serialize=False, verbose_name='Ключ'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(default='', max_length=255, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Нет категории', max_length=128, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Статья',
                                    to='articles.article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(default='ici', verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateField(auto_now_add=True, db_index=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='guid',
            field=models.CharField(db_column='guid', default=uuid.uuid4, editable=False, max_length=64,
                                   primary_key=True, serialize=False, verbose_name='Ключ'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_added',
            field=models.TimeField(auto_now_add=True, db_index=True, verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Автор',
                                    to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='guid',
            field=models.CharField(db_column='guid', default=uuid.uuid4, editable=False, max_length=64,
                                   primary_key=True, serialize=False, verbose_name='Ключ'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='guid',
            field=models.CharField(db_column='guid', default=uuid.uuid4, editable=False, max_length=64,
                                   primary_key=True, serialize=False, verbose_name='Ключ'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(default='', max_length=512, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message_readed',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
    ]
