# Generated by Django 4.1.2 on 2022-11-02 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0024_alter_article_article_body_alter_article_author_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Создатель',
                                    to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Получатель',
                                    to=settings.AUTH_USER_MODEL, verbose_name='Получатель'),
        ),
    ]
