# Generated by Django 4.1.2 on 2022-11-03 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0025_alter_notification_author_id_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='article',
            new_name='articles_blocked_a280a5_idx',
            old_name='articles_ar_blocked_286596_idx',
        ),
        migrations.RenameIndex(
            model_name='article',
            new_name='articles_moderat_7d6055_idx',
            old_name='articles_ar_moderat_f293b2_idx',
        ),
        migrations.RenameIndex(
            model_name='articlehistory',
            new_name='article_his_change__046c06_idx',
            old_name='articles_ar_change__541634_idx',
        ),
        migrations.RenameIndex(
            model_name='articlelike',
            new_name='article_lik_dts_83878c_idx',
            old_name='articles_ar_dts_d3ee4e_idx',
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='categories_name_98d7d5_idx',
            old_name='articles_ca_name_b48539_idx',
        ),
        migrations.RenameIndex(
            model_name='commentlike',
            new_name='comment_lik_dts_3dfdb8_idx',
            old_name='articles_co_dts_f3536f_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_dts_b1ccff_idx',
            old_name='articles_no_dts_decc32_idx',
        ),
        migrations.AlterModelTable(
            name='article',
            table='articles',
        ),
        migrations.AlterModelTable(
            name='articlecategory',
            table='article_categories',
        ),
        migrations.AlterModelTable(
            name='articlehistory',
            table='article_history',
        ),
        migrations.AlterModelTable(
            name='articlelike',
            table='article_likes',
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
        migrations.AlterModelTable(
            name='commentlike',
            table='comment_likes',
        ),
        migrations.AlterModelTable(
            name='notification',
            table='notifications',
        ),
    ]
