# Generated by Django 4.1.2 on 2022-11-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0027_rename_articles_blocked_a280a5_idx_article_blocked_4b1e21_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publication',
            field=models.BooleanField(default=False, verbose_name='Видимость статьи'),
        ),
    ]
