# Generated by Django 4.1.3 on 2022-11-08 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0028_article_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentComment',
            fields=[
                ('guid', models.CharField(db_column='guid', default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False, verbose_name='Ключ')),
                ('body', models.TextField(default='ici', verbose_name='Содержимое')),
                ('date_added', models.DateField(auto_now_add=True, db_index=True, verbose_name='Дата добавления')),
                ('time_added', models.TimeField(auto_now_add=True, db_index=True, verbose_name='Время добавления')),
                ('comment_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.comment', verbose_name='Комментарий')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Комментарий для комментария',
                'verbose_name_plural': 'Комментарии для комментариев',
                'db_table': 'comment_for_comment',
                'ordering': ['comment_uid', 'date_added', 'time_added'],
            },
        ),
    ]
