# Generated by Django 4.1.3 on 2022-11-08 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0029_commentcomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentComment',
            new_name='SubComment',
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='comment_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.comment', verbose_name='Комментарий'),
        ),
        migrations.AlterModelTable(
            name='subcomment',
            table='sub_comment',
        ),
        migrations.CreateModel(
            name='SubCommentLike',
            fields=[
                ('guid', models.CharField(db_column='guid', default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False, verbose_name='Ключ')),
                ('date_added', models.DateField(db_column='dts', default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('event_counter', models.IntegerField(default=1, verbose_name='Счетчик')),
                ('comment_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.comment', verbose_name='Комментарий')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Лайк (доп комментария)',
                'verbose_name_plural': 'Лайки (доп комментариев)',
                'db_table': 'sub_comment_like',
            },
        ),
        migrations.AddIndex(
            model_name='subcommentlike',
            index=models.Index(fields=['date_added'], name='sub_comment_dts_8f89c5_idx'),
        ),
        migrations.AddConstraint(
            model_name='subcommentlike',
            constraint=models.UniqueConstraint(fields=('user_id', 'comment_uid'), name='articles_subcommentlike_unique'),
        ),
    ]
